#!/usr/bin/env bash
# Bake every Qt ShaderEffect host in shaders/*.frag → matching .qsb, and
# inline GLES wrappers (shiny + ripple) into hypr/src/shaders.hpp.
# Qt hosts: GLSL 440 ShaderEffect files. GLES (*gles*) and lighting includes
# are not qsb inputs.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
shader_dir="$root/shaders"
lighting="$shader_dir/shiny-lighting.frag"
ripple_lighting="$shader_dir/ripple-lighting.frag"
gles_src="$shader_dir/shiny.gles.frag"
ripple_gles_src="$shader_dir/ripple.gles.frag"
vert_src="$shader_dir/shiny.gles.vert"
out_hpp="$root/hypr/src/shaders.hpp"

if [[ -n "${QSB:-}" ]]; then
  qsb="$QSB"
elif command -v qsb >/dev/null 2>&1; then
  qsb=$(command -v qsb)
elif [[ -x /usr/lib/qt6/bin/qsb ]]; then
  qsb=/usr/lib/qt6/bin/qsb
else
  echo "qsb not found (qt6-shadertools). Set QSB= or put qsb on PATH." >&2
  exit 1
fi

for f in "$lighting" "$ripple_lighting" "$gles_src" "$ripple_gles_src" "$vert_src"; do
  if [[ ! -f $f ]]; then
    echo "missing $f" >&2
    exit 1
  fi
done

expand_includes() {
  python3 - "$1" <<'PY'
import os, re, sys

path = sys.argv[1]
include_re = re.compile(r'^[ \t]*#include[ \t]+"([^"]+)"[ \t]*\n?', re.M)

def expand(p, stack):
    p = os.path.abspath(p)
    if p in stack:
        raise SystemExit("include cycle: " + p)
    if not os.path.isfile(p):
        raise SystemExit("missing include " + p)
    text = open(p, encoding="utf-8").read()
    root = os.path.dirname(p)

    def repl(m):
        inc = m.group(1)
        ip = inc if os.path.isabs(inc) else os.path.join(root, inc)
        body = expand(ip, stack + [p])
        if body and not body.endswith("\n"):
            body += "\n"
        return body

    return include_re.sub(repl, text)

sys.stdout.write(expand(path, []))
PY
}

is_qt_host() {
  local f="$1"
  local base
  base=$(basename "$f")
  case "$base" in
    *.gles.frag|*-lighting.frag) return 1 ;;
  esac
  grep -q 'qt_TexCoord0' "$f"
}

qt_frags=()
while IFS= read -r f; do
  if is_qt_host "$f"; then
    qt_frags+=("$f")
  fi
done < <(find "$shader_dir" -maxdepth 1 -type f -name '*.frag' | sort)

if (( ${#qt_frags[@]} == 0 )); then
  echo "no Qt ShaderEffect hosts in $shader_dir" >&2
  exit 1
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

for qt_src in "${qt_frags[@]}"; do
  base=$(basename "$qt_src")
  expanded="$tmpdir/$base"
  expand_includes "$qt_src" > "$expanded"
  out_qsb="$shader_dir/${base}.qsb"
  "$qsb" --glsl "100es,120,150" --hlsl 50 --msl 12 -o "$out_qsb" "$expanded"
  echo "baked $out_qsb"
done

python3 - "$vert_src" "$gles_src" "$ripple_gles_src" "$out_hpp" <<'PY'
import os, re, sys

vert_path, gles_path, ripple_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
include_re = re.compile(r'^[ \t]*#include[ \t]+"([^"]+)"[ \t]*\n?', re.M)

def expand(p, stack):
    p = os.path.abspath(p)
    if p in stack:
        raise SystemExit("include cycle: " + p)
    if not os.path.isfile(p):
        raise SystemExit("missing include " + p)
    text = open(p, encoding="utf-8").read()
    root = os.path.dirname(p)

    def repl(m):
        inc = m.group(1)
        ip = inc if os.path.isabs(inc) else os.path.join(root, inc)
        body = expand(ip, stack + [p])
        if body and not body.endswith("\n"):
            body += "\n"
        return body

    return include_re.sub(repl, text)

vert = open(vert_path, encoding="utf-8").read()
frag = expand(gles_path, [])
ripple = expand(ripple_path, [])
if ")SHINYVERT" in vert:
    raise SystemExit("raw-string delimiter )SHINYVERT appears in vertex source")
if ")SHINYFRAG" in frag:
    raise SystemExit("raw-string delimiter )SHINYFRAG appears in fragment source")
if ")RIPPLEFRAG" in ripple:
    raise SystemExit("raw-string delimiter )RIPPLEFRAG appears in ripple fragment source")

hpp = (
    "#pragma once\n\n"
    "#include <string>\n\n"
    "// Generated by scripts/bake.sh from shaders/shiny.gles.vert,\n"
    "// shaders/shiny.gles.frag (includes shaders/shiny-lighting.frag),\n"
    "// and shaders/ripple.gles.frag (includes shaders/ripple-lighting.frag).\n"
    "// Do not edit the fragment lighting bodies here — change the lighting\n"
    "// source and re-run bake.\n\n"
    "// Hyprland tex300.vert — unit quad, proj maps it onto the decoration box.\n"
    "// Ripple reuses this vertex program.\n"
    "inline const std::string SHINY_VERT = R\"SHINYVERT("
    + vert
    + ")SHINYVERT\";\n\n"
    "// GLES 3 wrapper (CShader uniforms, gl_FragCoord, alpha) around the\n"
    "// shared lighting body. Qt's host is shaders/shiny.frag.\n"
    "inline const std::string SHINY_FRAG = R\"SHINYFRAG("
    + frag
    + ")SHINYFRAG\";\n\n"
    "// GLES 3 ripple sibling. Qt's host is shaders/ripple.frag.\n"
    "inline const std::string RIPPLE_FRAG = R\"RIPPLEFRAG("
    + ripple
    + ")RIPPLEFRAG\";\n"
)

tmp = out_path + ".tmp." + str(os.getpid())
with open(tmp, "w", encoding="utf-8") as f:
    f.write(hpp)
os.replace(tmp, out_path)
print("inlined " + out_path)
PY

if [[ "${1:-}" == "--dump" || "${1:-}" == "-d" ]]; then
  "$qsb" -d "$shader_dir/shiny.frag.qsb"
fi
