#!/usr/bin/env bash
# Bake shaders/shiny.frag → shaders/shiny.frag.qsb for Qt 6 ShaderEffect,
# and inline shaders/shiny-lighting.frag into hypr/src/shaders.hpp.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
qt_src="$root/shaders/shiny.frag"
lighting="$root/shaders/shiny-lighting.frag"
gles_src="$root/shaders/shiny.gles.frag"
vert_src="$root/shaders/shiny.gles.vert"
out_qsb="$root/shaders/shiny.frag.qsb"
out_hpp="$root/hypr/src/shaders.hpp"

if [[ -n "${QSB:-}" ]]; then
  qsb="$QSB"
elif command -v qsb >/dev/null 2>&1; then
  qsb=$(command -v qsb)
elif [[ -x /usr/lib/qt6/bin/qsb ]]; then
  qsb=/usr/lib/qt6/bin/qsb
else
  echo "qsb not found (qt6-shadertools). Set QSB= or put qsb on PATH." >&2
  exit 1
fi

for f in "$qt_src" "$lighting" "$gles_src" "$vert_src"; do
  if [[ ! -f $f ]]; then
    echo "missing $f" >&2
    exit 1
  fi
done

expand_includes() {
  python3 - "$1" <<'PY'
import os, re, sys

path = sys.argv[1]
include_re = re.compile(r'^[ \t]*#include[ \t]+"([^"]+)"[ \t]*\n?', re.M)

def expand(p, stack):
    p = os.path.abspath(p)
    if p in stack:
        raise SystemExit("include cycle: " + p)
    if not os.path.isfile(p):
        raise SystemExit("missing include " + p)
    text = open(p, encoding="utf-8").read()
    root = os.path.dirname(p)

    def repl(m):
        inc = m.group(1)
        ip = inc if os.path.isabs(inc) else os.path.join(root, inc)
        body = expand(ip, stack + [p])
        if body and not body.endswith("\n"):
            body += "\n"
        return body

    return include_re.sub(repl, text)

sys.stdout.write(expand(path, []))
PY
}

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT
expanded_qt="$tmpdir/shiny.frag"
expand_includes "$qt_src" > "$expanded_qt"

"$qsb" --glsl "100es,120,150" --hlsl 50 --msl 12 -o "$out_qsb" "$expanded_qt"
echo "baked $out_qsb"

python3 - "$vert_src" "$gles_src" "$out_hpp" <<'PY'
import os, re, sys

vert_path, gles_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
include_re = re.compile(r'^[ \t]*#include[ \t]+"([^"]+)"[ \t]*\n?', re.M)

def expand(p, stack):
    p = os.path.abspath(p)
    if p in stack:
        raise SystemExit("include cycle: " + p)
    if not os.path.isfile(p):
        raise SystemExit("missing include " + p)
    text = open(p, encoding="utf-8").read()
    root = os.path.dirname(p)

    def repl(m):
        inc = m.group(1)
        ip = inc if os.path.isabs(inc) else os.path.join(root, inc)
        body = expand(ip, stack + [p])
        if body and not body.endswith("\n"):
            body += "\n"
        return body

    return include_re.sub(repl, text)

vert = open(vert_path, encoding="utf-8").read()
frag = expand(gles_path, [])
if ")SHINYVERT" in vert:
    raise SystemExit("raw-string delimiter )SHINYVERT appears in vertex source")
if ")SHINYFRAG" in frag:
    raise SystemExit("raw-string delimiter )SHINYFRAG appears in fragment source")

hpp = (
    "#pragma once\n\n"
    "#include <string>\n\n"
    "// Generated by scripts/bake.sh from shaders/shiny.gles.vert and\n"
    "// shaders/shiny.gles.frag (which includes shaders/shiny-lighting.frag).\n"
    "// Do not edit the fragment lighting body here — change the lighting\n"
    "// source and re-run bake.\n\n"
    "// Hyprland tex300.vert — unit quad, proj maps it onto the decoration box.\n"
    "inline const std::string SHINY_VERT = R\"SHINYVERT("
    + vert
    + ")SHINYVERT\";\n\n"
    "// GLES 3 wrapper (CShader uniforms, gl_FragCoord, alpha) around the\n"
    "// shared lighting body. Qt's host is shaders/shiny.frag.\n"
    "inline const std::string SHINY_FRAG = R\"SHINYFRAG("
    + frag
    + ")SHINYFRAG\";\n"
)

tmp = out_path + ".tmp." + str(os.getpid())
with open(tmp, "w", encoding="utf-8") as f:
    f.write(hpp)
os.replace(tmp, out_path)
print("inlined " + out_path)
PY

if [[ "${1:-}" == "--dump" || "${1:-}" == "-d" ]]; then
  "$qsb" -d "$out_qsb"
fi
