//! Emit `~/.config/hypr/border-fx.lua` from a resolved look. This is the only
//! place that knows both schemas: camelCase JSON keys in, snake_case
//! `plugin.shiny_border` Hyprland adapter keys out.

use serde_json::Value;

use crate::look::{Look, color, effect_draws};

pub struct LuaOpts<'a> {
    pub plugin_id: &'a str,
    pub plugin_name: &'a str,
    pub session_so: &'a str,
    /// Emit the `hl.plugin.load` on `hyprland.start`.
    pub load: bool,
    /// `enabled = true` in the adapter table.
    pub enabled: bool,
}

pub fn lua_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

fn lua_bool(v: &Value) -> &'static str {
    if v.as_bool() == Some(true) { "true" } else { "false" }
}

fn lua_num(v: &Value) -> String {
    match v {
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => match n.as_f64() {
            Some(f) if f.is_finite() => {
                if f.fract() == 0.0 && f.abs() < 9.0e15 {
                    format!("{}", f as i64)
                } else {
                    format!("{f}")
                }
            }
            _ => "0".to_string(),
        },
        Value::String(s) => match s.trim().parse::<f64>() {
            Ok(f) if f.is_finite() => lua_num(&crate::look::schema::num(f)),
            _ => "0".to_string(),
        },
        _ => "0".to_string(),
    }
}

fn lua_colors(values: &[Value]) -> String {
    let inner: Vec<String> = values.iter().map(|c| lua_str(&color::to_hypr(c))).collect();
    format!("{{ colors = {{ {} }} }}", inner.join(", "))
}

fn ramp_or_col_a(look: &Look, key: &str) -> String {
    let list = color::as_list(&look[key]);
    if list.len() < 2 { lua_colors(std::slice::from_ref(&look["colA"])) } else { lua_colors(&list) }
}

fn str_of(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Null => String::new(),
        other => other.to_string(),
    }
}

/// `dofile("<path>")` with the path escaped as a Lua string literal.
pub fn dofile_expr(path: &str) -> String {
    format!("dofile({})", lua_str(path))
}

pub fn render(look: &Look, o: &LuaOpts) -> String {
    let effect = str_of(&look["effect"]);
    let draws = effect_draws(&effect);
    let load = o.load && draws;
    let enabled = o.enabled && draws;
    let n = |k: &str| lua_num(&look[k]);
    let b = |k: &str| lua_bool(&look[k]);
    let c = |k: &str| lua_str(&color::to_hypr(&look[k]));

    let lines: Vec<String> = vec![
        format!("-- Generated by {} (border-fx apply). Do not edit.", o.plugin_id),
        format!("-- Source of truth: ~/.config/omarchy/shell.json plugins[] entry id {}.", o.plugin_id),
        format!(
            "-- Effect {} fans out to the Hyprland adapter (plugin:shiny-border / shiny_border) when effect is shiny or ripple.",
            lua_str(&effect)
        ),
        String::new(),
        "hl.permission({ binary = \"/usr/(bin|local/bin)/hyprctl\", type = \"plugin\", mode = \"allow\" })".into(),
        String::new(),
        format!("local SHINY_SO = {}", lua_str(o.session_so)),
        format!("local SHINY_LOAD = {}", if load { "true" } else { "false" }),
        String::new(),
        "local function shinyLoaded()".into(),
        "  for _, p in ipairs(hl.get_loaded_plugins()) do".into(),
        format!("    if p.name == {} then", lua_str(o.plugin_name)),
        "      return true".into(),
        "    end".into(),
        "  end".into(),
        "  return false".into(),
        "end".into(),
        String::new(),
        "-- Load on hyprland.start, not during parse: PLUGIN_INIT reloads config.".into(),
        "if SHINY_LOAD and not _G.__wmfeht_border_fx_start then".into(),
        "  _G.__wmfeht_border_fx_start = true".into(),
        "  hl.on(\"hyprland.start\", function()".into(),
        "    if shinyLoaded() then".into(),
        "      return".into(),
        "    end".into(),
        "    local f = io.open(SHINY_SO, \"r\")".into(),
        "    if not f then".into(),
        "      return".into(),
        "    end".into(),
        "    f:close()".into(),
        "    hl.plugin.load(SHINY_SO)".into(),
        "  end)".into(),
        "end".into(),
        String::new(),
        "if shinyLoaded() then".into(),
        "  hl.config({".into(),
        "    plugin = {".into(),
        "      shiny_border = {".into(),
        format!("        enabled      = {},", if enabled { "true" } else { "false" }),
        format!("        effect       = {},", lua_str(&effect)),
        format!("        active_only  = {},", b("activeOnly")),
        format!("        pulse        = {},", b("pulse")),
        format!("        pulse_hz     = {},", n("pulseHz")),
        format!("        ripple_freq  = {},", n("rippleFreq")),
        format!("        ripple_speed = {},", n("rippleSpeed")),
        format!("        ripple_gain  = {},", n("rippleGain")),
        format!("        ripple_power = {},", n("ripplePower")),
        format!("        ripple_origin_x = {},", n("rippleOriginX")),
        format!("        ripple_origin_y = {},", n("rippleOriginY")),
        format!("        ripple_fade  = {},", n("rippleFade")),
        format!("        shimmer      = {},", b("shimmer")),
        format!("        shimmer_hz   = {},", n("shimmerHz")),
        format!("        shimmer_deg  = {},", n("shimmerDeg")),
        format!("        shimmer_scale_min = {},", n("shimmerScaleMin")),
        format!("        shimmer_scale_max = {},", n("shimmerScaleMax")),
        format!("        pin_deg      = {},", n("pinDeg")),
        format!("        angle_offset = {},", n("angleOffset")),
        format!("        lobe         = {},", n("lobe")),
        format!("        mirror       = {},", b("mirror")),
        format!("        specular_halo = {},", b("specularHalo")),
        format!("        border_size  = {},", n("borderSize")),
        "        col = {".into(),
        format!("          a = {},", c("colA")),
        format!("          b = {},", c("colB")),
        "        },".into(),
        format!("        base_color            = {},", c("baseColor")),
        format!("        gradient              = {},", ramp_or_col_a(look, "gradient")),
        format!("        gradient_positions    = {},", lua_str(&str_of(&look["gradientPositions"]))),
        format!("        gradient_cw           = {},", ramp_or_col_a(look, "gradientCw")),
        format!("        gradient_positions_cw = {},", lua_str(&str_of(&look["gradientPositionsCw"]))),
        "      },".into(),
        "    },".into(),
        "  })".into(),
        "end".into(),
        String::new(),
    ];
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::look::resolve_shared;
    use serde_json::json;

    fn opts() -> LuaOpts<'static> {
        LuaOpts {
            plugin_id: "wmfeht.border-fx",
            plugin_name: "hypr-shiny-border",
            session_so: "/tmp/omarchy-border-fx-test.so",
            load: true,
            enabled: true,
        }
    }

    fn assign<'a>(lua: &'a str, key: &str) -> Option<&'a str> {
        lua.lines().find_map(|l| {
            let t = l.trim_start();
            let rest = t.strip_prefix(key)?.trim_start();
            let rest = rest.strip_prefix('=')?.trim();
            Some(rest.trim_end_matches(','))
        })
    }

    #[test]
    fn default_look() {
        let (look, _) = resolve_shared(&json!({}));
        let lua = render(&look, &opts());
        assert!(lua.contains("wmfeht.border-fx"));
        assert!(lua.contains("shiny_border"));
        assert_eq!(assign(&lua, "border_size"), Some("2"));
        assert_eq!(assign(&lua, "pin_deg"), Some("120"));
        assert_eq!(assign(&lua, "pulse"), Some("false"));
        assert_eq!(assign(&lua, "shimmer"), Some("true"));
        assert_eq!(assign(&lua, "mirror"), Some("true"));
        assert_eq!(assign(&lua, "shimmer_hz"), Some("0.28"));
        assert_eq!(assign(&lua, "ripple_origin_x"), Some("0.5"));
        assert_eq!(assign(&lua, "ripple_fade"), Some("0"));
        assert_eq!(assign(&lua, "specular_halo"), Some("false"));
        assert_eq!(assign(&lua, "base_color"), Some("\"rgba(0a3f47dd)\""));
        assert!(lua.contains("rgba(f7ffffee)"));
        assert!(lua.contains("hl.plugin.load"));
        assert!(lua.contains("hyprland.start"));
        assert!(lua.contains("__wmfeht_border_fx_start"));
        assert!(lua.contains("SHINY_LOAD = true"));
        assert!(lua.contains("/tmp/omarchy-border-fx-test.so"));
        assert!(!lua.contains("mouse") && !lua.contains("cursor") && !lua.contains("quantize_deg"));
        assert!(!lua.lines().any(|l| l.trim_start().starts_with("pin ")));
        assert!(lua.ends_with("end\n"));
    }

    #[test]
    fn disabled_and_non_drawing() {
        let (look, _) = resolve_shared(&json!({}));
        let lua = render(&look, &LuaOpts { load: false, enabled: false, ..opts() });
        assert!(lua.contains("SHINY_LOAD = false"));
        assert_eq!(assign(&lua, "enabled"), Some("false"));

        let (other, _) = resolve_shared(&json!({"effect": "other"}));
        let lua = render(&other, &opts());
        assert!(lua.contains("SHINY_LOAD = false"));
        assert_eq!(assign(&lua, "enabled"), Some("false"));

        let (ripple, _) = resolve_shared(&json!({"effect": "ripple"}));
        let lua = render(&ripple, &opts());
        assert!(lua.contains("SHINY_LOAD = true"));
        assert_eq!(assign(&lua, "enabled"), Some("true"));
        assert_eq!(assign(&lua, "effect"), Some("\"ripple\""));
        assert_eq!(assign(&lua, "ripple_freq"), Some("0.025"));
        assert_eq!(assign(&lua, "ripple_speed"), Some("2"));
        assert_eq!(assign(&lua, "ripple_gain"), Some("0.85"));
        assert_eq!(assign(&lua, "ripple_power"), Some("8"));
    }

    #[test]
    fn colors_and_ramps() {
        let (look, _) =
            resolve_shared(&json!({"colA": "rgba(33ccffe)", "colB": "rgba(00ff99)", "baseColor": "rgba(00687855)"}));
        let lua = render(&look, &opts());
        assert!(lua.contains("a = \"rgba(00000000)\""));
        assert!(lua.contains("b = \"rgba(00ff99ff)\""));
        assert!(lua.contains("base_color            = \"rgba(00687855)\""));

        let (empty_ramp, _) = resolve_shared(&json!({"gradient": [], "colA": "rgba(11223344)"}));
        let lua = render(&empty_ramp, &opts());
        assert!(lua.contains("gradient              = { colors = { \"rgba(11223344)\" } }"));
        assert!(lua.contains("gradient_cw           = { colors = { \"rgba(11223344)\" } }"));

        let (cw, _) = resolve_shared(&json!({"gradientCw": ["#ff112233", "rgb(445566)"]}));
        let lua = render(&cw, &opts());
        assert!(lua.contains("gradient_cw           = { colors = { \"rgba(112233ff)\", \"rgba(445566ff)\" } }"));
    }

    #[test]
    fn numbers_are_lua_safe() {
        let (look, _) =
            resolve_shared(&json!({"lobe": 1, "angleOffset": 10.7, "shimmerDeg": 20.2, "borderSize": "inf"}));
        let lua = render(&look, &opts());
        assert_eq!(assign(&lua, "lobe"), Some("0.5"));
        assert_eq!(assign(&lua, "angle_offset"), Some("11"));
        assert_eq!(assign(&lua, "shimmer_deg"), Some("20"));
        assert_eq!(assign(&lua, "border_size"), Some("2"));
        assert!(!lua.contains("inf") && !lua.contains("nan") && !lua.contains("Infinity"));
    }

    #[test]
    fn escaping() {
        assert_eq!(lua_str("a\"b\\c"), "\"a\\\"b\\\\c\"");
        assert_eq!(dofile_expr("/x/with]=]bracket/f.lua"), "dofile(\"/x/with]=]bracket/f.lua\")");
        assert_eq!(dofile_expr("/q\"uote"), "dofile(\"/q\\\"uote\")");
    }
}
